-- MySQL Script generated by MySQL Workbench
-- Fri Jul 29 15:58:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema watermonitor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema watermonitor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `watermonitor` DEFAULT CHARACTER SET utf8 ;
USE `watermonitor` ;

-- -----------------------------------------------------
-- Table `watermonitor`.`tank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watermonitor`.`tank` (
  `id` BIGINT(60) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(100) NULL,
  `date` DATETIME NULL,
  `water_level` VARCHAR(45) NULL,
  `register_status` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `watermonitor`.`daily_control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watermonitor`.`daily_control` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATE NOT NULL,
  `water_level` VARCHAR(45) NULL,
  `register_status` TINYINT NULL,
  `tank_id` BIGINT(60) NOT NULL,
  PRIMARY KEY (`id`, `tank_id`),
  INDEX `fk_daily_control_tank_idx` (`tank_id` ASC) VISIBLE,
  CONSTRAINT `fk_daily_control_tank`
    FOREIGN KEY (`tank_id`)
    REFERENCES `watermonitor`.`tank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `watermonitor`.`hydrometer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watermonitor`.`hydrometer` (
  `id` BIGINT(60) NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(60) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `display` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `watermonitor`.`reading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `watermonitor`.`reading` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `consume` INT NOT NULL,
  `reading` INT NOT NULL,
  `hydrometer_id` BIGINT(60) NOT NULL,
  PRIMARY KEY (`id`, `hydrometer_id`),
  INDEX `fk_reading_hydrometer1_idx` (`hydrometer_id` ASC) VISIBLE,
  CONSTRAINT `fk_reading_hydrometer1`
    FOREIGN KEY (`hydrometer_id`)
    REFERENCES `watermonitor`.`hydrometer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
